const FORMULAS=[
  {
    "id": "quadratische-gleichung",
    "title": "Quadratische Gleichung",
    "category": "Mathematische Grundlagen",
    "formula": "x_{1,2}=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}",
    "explanation": "Nullstellen einer quadratischen Gleichung.",
    "symbols": "a, b, c: Koeffizienten; x: Lösung",
    "tip": "Der Ausdruck unter der Wurzel ist die Diskriminante.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "dreisatz",
    "title": "Proportionaler Dreisatz",
    "category": "Mathematische Grundlagen",
    "formula": "x=\\frac{b\\cdot c}{a}",
    "explanation": "Berechnet eine unbekannte proportionale Größe.",
    "symbols": "a, b, c: bekannte Werte; x: gesuchter Wert",
    "tip": "Nur bei direkter Proportionalität anwenden.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "geschwindigkeit",
    "title": "Geschwindigkeit",
    "category": "Physikalische Grundlagen",
    "formula": "v=\\frac{s}{t}",
    "explanation": "Weg pro benötigter Zeit.",
    "symbols": "v [m/s]; s [m]; t [s]",
    "tip": "km/h durch 3,6 ergibt m/s.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "beschleunigung",
    "title": "Beschleunigung",
    "category": "Physikalische Grundlagen",
    "formula": "a=\\frac{\\Delta v}{\\Delta t}",
    "explanation": "Änderung der Geschwindigkeit pro Zeit.",
    "symbols": "a [m/s²]; Δv [m/s]; Δt [s]",
    "tip": "Negative Werte beschreiben bei gleicher Bezugsrichtung eine Verzögerung.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "kraft",
    "title": "Kraft",
    "category": "Mechanik",
    "formula": "F=m\\cdot a",
    "explanation": "Kraft beschleunigt eine Masse.",
    "symbols": "F [N]; m [kg]; a [m/s²]",
    "tip": "1 N = 1 kg·m/s².",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "drehmoment",
    "title": "Drehmoment",
    "category": "Mechanik",
    "formula": "M=F\\cdot r",
    "explanation": "Drehende Wirkung einer Kraft.",
    "symbols": "M [Nm]; F [N]; r [m]",
    "tip": "Die Kraft muss senkrecht zum Hebelarm wirken.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "arbeit",
    "title": "Mechanische Arbeit",
    "category": "Mechanik",
    "formula": "W=F\\cdot s",
    "explanation": "Arbeit bei Kraftwirkung entlang eines Weges.",
    "symbols": "W [J]; F [N]; s [m]",
    "tip": "Bei einem Winkel gilt W = F·s·cos(α).",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "mech-leistung",
    "title": "Mechanische Leistung",
    "category": "Mechanik",
    "formula": "P=\\frac{W}{t}",
    "explanation": "Verrichtete Arbeit pro Zeit.",
    "symbols": "P [W]; W [J]; t [s]",
    "tip": "1 W = 1 J/s.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "rotationsleistung",
    "title": "Leistung einer rotierenden Welle",
    "category": "Motoren",
    "formula": "P=M\\cdot\\omega=M\\cdot2\\pi\\frac{n}{60}",
    "explanation": "Verknüpft Drehmoment, Drehzahl und Wellenleistung.",
    "symbols": "P [W]; M [Nm]; ω [rad/s]; n [1/min]",
    "tip": "Praxisformel: P [kW] = M·n/9550.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "motordrehmoment",
    "title": "Motordrehmoment aus Leistung",
    "category": "Motoren",
    "formula": "M=\\frac{9550\\cdot P}{n}",
    "explanation": "Drehmoment aus Leistung und Drehzahl.",
    "symbols": "M [Nm]; P [kW]; n [1/min]",
    "tip": "9550 gilt bei P in kW und n in 1/min.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "winkelgeschwindigkeit",
    "title": "Winkelgeschwindigkeit",
    "category": "Motoren",
    "formula": "\\omega=2\\pi\\frac{n}{60}",
    "explanation": "Drehzahl in Winkelgeschwindigkeit umrechnen.",
    "symbols": "ω [rad/s]; n [1/min]",
    "tip": "Eine Umdrehung entspricht 2π rad.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "motor-wirkungsgrad",
    "title": "Wirkungsgrad eines Motors",
    "category": "Motoren",
    "formula": "\\eta=\\frac{P_{mech}}{P_{el}}",
    "explanation": "Verhältnis von mechanischer Ausgangs- zu elektrischer Eingangsleistung.",
    "symbols": "η [-]; P [W]",
    "tip": "95 % als 0,95 einsetzen.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "uebersetzung",
    "title": "Getriebeübersetzung",
    "category": "Getriebe",
    "formula": "i=\\frac{n_1}{n_2}=\\frac{z_2}{z_1}=\\frac{d_2}{d_1}",
    "explanation": "Verhältnis von Antrieb und Abtrieb.",
    "symbols": "i [-]; n [1/min]; z [-]; d [mm]",
    "tip": "i > 1 bedeutet Untersetzung ins Langsame.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "abtriebsdrehzahl",
    "title": "Abtriebsdrehzahl",
    "category": "Getriebe",
    "formula": "n_2=\\frac{n_1}{i}",
    "explanation": "Drehzahl am Getriebeabtrieb.",
    "symbols": "n₂, n₁ [1/min]; i [-]",
    "tip": "Bei i > 1 ist n₂ kleiner als n₁.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "abtriebsdrehmoment",
    "title": "Abtriebsdrehmoment",
    "category": "Getriebe",
    "formula": "M_2=M_1\\cdot i\\cdot\\eta",
    "explanation": "Reales Abtriebsdrehmoment inklusive Verlusten.",
    "symbols": "M₂, M₁ [Nm]; i, η [-]",
    "tip": "Wirkungsgrad als Dezimalzahl einsetzen.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "gesamtuebersetzung",
    "title": "Gesamtübersetzung",
    "category": "Getriebe",
    "formula": "i_{ges}=i_1\\cdot i_2\\cdot\\ldots\\cdot i_k",
    "explanation": "Gesamtübersetzung mehrerer Stufen.",
    "symbols": "i [-]",
    "tip": "Einzelübersetzungen werden multipliziert.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "zahnradmodul",
    "title": "Zahnradmodul",
    "category": "Getriebe",
    "formula": "m=\\frac{d}{z}",
    "explanation": "Größe der Verzahnung.",
    "symbols": "m [mm]; d [mm]; z [-]",
    "tip": "Kämmende Zahnräder benötigen denselben Modul.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "ohm",
    "title": "Ohmsches Gesetz",
    "category": "Elektrotechnik",
    "formula": "U=R\\cdot I",
    "explanation": "Zusammenhang von Spannung, Widerstand und Strom.",
    "symbols": "U [V]; R [Ω]; I [A]",
    "tip": "Umstellungen: I=U/R und R=U/I.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "leistung-dc",
    "title": "Elektrische Leistung bei Gleichstrom",
    "category": "Elektrotechnik",
    "formula": "P=U\\cdot I",
    "explanation": "Elektrische Leistung bei Gleichspannung.",
    "symbols": "P [W]; U [V]; I [A]",
    "tip": "Auch P=I²R und P=U²/R.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "drehstrom",
    "title": "Wirkleistung im Drehstromnetz",
    "category": "Elektrotechnik",
    "formula": "P=\\sqrt{3}\\cdot U\\cdot I\\cdot\\cos(\\varphi)",
    "explanation": "Wirkleistung eines symmetrischen Drehstromsystems.",
    "symbols": "P [W]; U [V]; I [A]; cos φ [-]",
    "tip": "Für Motoren gegebenenfalls Wirkungsgrad berücksichtigen.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "el-arbeit",
    "title": "Elektrische Arbeit",
    "category": "Elektrotechnik",
    "formula": "W=P\\cdot t",
    "explanation": "Elektrische Energie aus Leistung und Zeit.",
    "symbols": "W [Wh oder J]; P [W]; t [h oder s]",
    "tip": "Einheiten konsistent verwenden.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "regeldifferenz",
    "title": "Regeldifferenz",
    "category": "Regelungstechnik",
    "formula": "e(t)=w(t)-x(t)",
    "explanation": "Abweichung zwischen Soll- und Istwert.",
    "symbols": "e: Differenz; w: Sollwert; x: Istwert",
    "tip": "Der Regler versucht e(t) zu verkleinern.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "p-regler",
    "title": "P-Regler",
    "category": "Regelungstechnik",
    "formula": "u(t)=K_P\\cdot e(t)",
    "explanation": "Stellgröße proportional zur Regeldifferenz.",
    "symbols": "u: Stellgröße; Kp: Verstärkung; e: Differenz",
    "tip": "Großes Kp kann Schwingungen fördern.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "prozent",
    "title": "Prozentwert",
    "category": "Einheiten und Umrechnungen",
    "formula": "W=G\\cdot\\frac{p}{100}",
    "explanation": "Prozentwert aus Grundwert und Prozentsatz.",
    "symbols": "W: Prozentwert; G: Grundwert; p [%]",
    "tip": "10 % entspricht 0,10.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  },
  {
    "id": "frequenz",
    "title": "Drehzahl in Frequenz",
    "category": "Einheiten und Umrechnungen",
    "formula": "f=\\frac{n}{60}",
    "explanation": "Umdrehungen pro Minute in Hertz.",
    "symbols": "f [Hz]; n [1/min]",
    "tip": "3000 1/min entsprechen 50 Hz.",
    "source": "Technische Grundformel",
    "updated": "07.10.2026"
  }
];
